### ISSUE TITLE
Request: Confirmation on exiting Edit Mode

### ISSUE THREAD

**Issue by SmilleyMLK** [UltraStar-Deluxe/DevOps#24]
There have been a few times when I've edited a song and pressed Esc once too often and had to redo several lines. I use/abuse the save key, but by Murphy's Law, such things happen when I don't. 
Anyway, an "Are you sure?" pop-up window or prompt would be nice, maybe along with a "Save unsaved changes" checkbox.

**Comment by basisbit** [comment]
this is now implemented with the updated editor from the usdx medley mod.
