### ISSUE TITLE
Request: Help message for hotkeys

### ISSUE THREAD

**Issue by SmilleyMLK** [UltraStar-Deluxe/DevOps#26]
In Ultrastar CMD, you can press F1 to display a list of every hotkey in Edit mode. This is extremely helpful, especially for rarely used features.

**Comment by basisbit** [comment]
should this help be english-only or also with translations in the language-files?

**Comment by SmilleyMLK** [comment]
I'm OK with either, though I guess it'd help to be translated, too.

**Comment by basisbit** [comment]
this is implemented in current USDX. Press [TAB] to show hotkey map.
