### ISSUE TITLE
Correct cover aspect ratios

### ISSUE THREAD

**Issue by MairusuPawa** [UltraStar-Deluxe/DevOps#34]
When Ultrastar was first released, it was designed with 4:3 screens in mind. Running the game on any other screen ratio will show deformed artworks, the most visible one being the covers in the current song selection wheel; they should be square, but they appear rectangular.

An easy way to cheat a correct aspect ratio in would be to deform the covers, and not render them as square in the first place; the game will be scaled to the screen and compensate for it. This could would be similar to the way anamorphic widescreen movies were stored on analog media designed for 4:3 back in the 90s. This isn't an ideal solution, but would probably be the quickest to implement and might still give decent results depending on the scaling quality.

**Comment by dracoTrier** [comment]
implemented a fix for roulette song selection view.

**Comment by basisbit** [comment]
implemented a fix for roulette song selection view.

**Comment by basisbit** [comment]
will reopen this issue later this year in the USDX sourcecode repo.
