### ISSUE TITLE
Feature Request: Audio level adjustment

### ISSUE THREAD

**Issue by SmilleyMLK** [UltraStar-Deluxe/DevOps#42]
While it's not a big problem on normal play, as you can adjust audio levels on Windows and the speakers as well, it would be a boon for recording purposes.

**Comment by dracoTrier** [comment]
sorry, but I don't see much reason for this. The OS audio mixer already provides you with many features you need in high quality resampling....

**Comment by basisbit** [comment]
sorry, but I don't see much reason for this. The OS audio mixer already provides you with many features you need in high quality resampling....
Also, please use the issue tracker in the repository USDX for any further issues.
