### ISSUE TITLE
package license information for used libraries

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/DevOps#5]
* FFmpeg - https://www.ffmpeg.org/doxygen/2.6/md_LICENSE.html - various
* Bass - http://www.un4seen.com/ - freeware for non commercial use, shareware/commercial license available from author
* SQLite - https://www.sqlite.org/copyright.html - public domain
* ProjectM - https://sourceforge.net/p/projectm/code/ci/master/tree/COPYING.txt - LGPL v2
* SDL 1.2 - LGPL v2.1
* Portaudio - http://www.portaudio.com/license.html - MIT license
* OpenGL - no licensing for app developers, only for hardware developers

**Comment by dracoTrier** [comment]
finished:
ffmpeg https://ffmpeg.zeranoe.com/builds/ - download 32-bit Shared GPL build
	GPLv2 https://www.ffmpeg.org/doxygen/2.8/md_LICENSE.html
Bass http://www.un4seen.com/download.php?bass24 - download standalone Bass v2.4.x
	freeware for non commercial use, shareware/commercial license available from www.un4seen.com
SQLite https://www.sqlite.org/download.html - download win32-x86
	Public Domain https://www.sqlite.org/copyright.html
ProjectM https://sourceforge.net/projects/projectm/files/
	GPLv2 https://sourceforge.net/p/projectm/code/ci/master/tree/COPYING.txt
SDL 1.2 https://www.libsdl.org/download-1.2.php
	LGPL v2.1
SDL-image 1.2 https://www.libsdl.org/projects/SDL_image/release-1.2.html
	zlib license
Portaudio only necessary for certain linux flavour
	own license v18 based on MIT license - http://www.portaudio.com/license.html - no need to publish their source code.
OpenGL - already licensed by graphics cards manufacturers
freetype http://www.freetype.org/download.html
	FTL or GPLv2
Lua http://www.lua.org/download.html
	MIT license http://www.lua.org/license.html

**Comment by basisbit** [comment]
finished:
ffmpeg https://ffmpeg.zeranoe.com/builds/ - download 32-bit Shared GPL build
	GPLv2 https://www.ffmpeg.org/doxygen/2.8/md_LICENSE.html
Bass http://www.un4seen.com/download.php?bass24 - download standalone Bass v2.4.x
	freeware for non commercial use, shareware/commercial license available from www.un4seen.com
SQLite https://www.sqlite.org/download.html - download win32-x86
	Public Domain https://www.sqlite.org/copyright.html
ProjectM https://sourceforge.net/projects/projectm/files/
	GPLv2 https://sourceforge.net/p/projectm/code/ci/master/tree/COPYING.txt
SDL 1.2 https://www.libsdl.org/download-1.2.php
	LGPL v2.1
SDL-image 1.2 https://www.libsdl.org/projects/SDL_image/release-1.2.html
	zlib license
Portaudio only necessary for certain linux flavour
	own license v18 based on MIT license - http://www.portaudio.com/license.html - no need to publish their source code.
OpenGL - already licensed by graphics cards manufacturers
freetype http://www.freetype.org/download.html
	FTL or GPLv2
Lua http://www.lua.org/download.html
	MIT license http://www.lua.org/license.html
